// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/confCenter/confCenter.proto

package go_micro_srv_confCenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ConfCenter service

type ConfCenterService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ConfCenter_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (ConfCenter_PingPongService, error)
}

type confCenterService struct {
	c    client.Client
	name string
}

func NewConfCenterService(name string, c client.Client) ConfCenterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.confCenter"
	}
	return &confCenterService{
		c:    c,
		name: name,
	}
}

func (c *confCenterService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConfCenter.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confCenterService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ConfCenter_StreamService, error) {
	req := c.c.NewRequest(c.name, "ConfCenter.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &confCenterServiceStream{stream}, nil
}

type ConfCenter_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type confCenterServiceStream struct {
	stream client.Stream
}

func (x *confCenterServiceStream) Close() error {
	return x.stream.Close()
}

func (x *confCenterServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *confCenterServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *confCenterServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *confCenterService) PingPong(ctx context.Context, opts ...client.CallOption) (ConfCenter_PingPongService, error) {
	req := c.c.NewRequest(c.name, "ConfCenter.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &confCenterServicePingPong{stream}, nil
}

type ConfCenter_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type confCenterServicePingPong struct {
	stream client.Stream
}

func (x *confCenterServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *confCenterServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *confCenterServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *confCenterServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *confCenterServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ConfCenter service

type ConfCenterHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, ConfCenter_StreamStream) error
	PingPong(context.Context, ConfCenter_PingPongStream) error
}

func RegisterConfCenterHandler(s server.Server, hdlr ConfCenterHandler, opts ...server.HandlerOption) error {
	type confCenter interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type ConfCenter struct {
		confCenter
	}
	h := &confCenterHandler{hdlr}
	return s.Handle(s.NewHandler(&ConfCenter{h}, opts...))
}

type confCenterHandler struct {
	ConfCenterHandler
}

func (h *confCenterHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ConfCenterHandler.Call(ctx, in, out)
}

func (h *confCenterHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ConfCenterHandler.Stream(ctx, m, &confCenterStreamStream{stream})
}

type ConfCenter_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type confCenterStreamStream struct {
	stream server.Stream
}

func (x *confCenterStreamStream) Close() error {
	return x.stream.Close()
}

func (x *confCenterStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *confCenterStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *confCenterStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *confCenterHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ConfCenterHandler.PingPong(ctx, &confCenterPingPongStream{stream})
}

type ConfCenter_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type confCenterPingPongStream struct {
	stream server.Stream
}

func (x *confCenterPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *confCenterPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *confCenterPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *confCenterPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *confCenterPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
